{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOCbFU5K2howyMfiHxtXRvA",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Atharva-AAS/Atharva-AAS/blob/main/olist-ecommerce-analysis/olist_business_queries.sql\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 15,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "N8fY_1bvRLOo",
        "outputId": "0dcd8156-c4d3-4a30-faba-607010928375"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)\n"
          ]
        }
      ],
      "source": [
        "!pip install duckdb\n",
        "import duckdb\n",
        "import pandas as pd\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "xGTOjIp8R3YB",
        "outputId": "af8a785c-6a06-4387-fddd-94c8a7bb430b"
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "\n",
        "print(\"Searching your Google Drive for the dataset files...\")\n",
        "found = False\n",
        "\n",
        "for root, dirs, files in os.walk(\"/content/drive/MyDrive\"):\n",
        "    if \"olist_orders_dataset.csv\" in files:\n",
        "        print(\"\\n✅ EXACT PATH FOUND:\")\n",
        "        print(f'base_path = \"{root}\"')\n",
        "        found = True\n",
        "        break\n",
        "\n",
        "if not found:\n",
        "    print(\"\\n❌ Could not find 'olist_orders_dataset.csv' anywhere in MyDrive.\")\n",
        "    print(\"Please double-check that you actually uploaded the dataset folder into your Google Drive account.\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "pHJtjp-TSXhB",
        "outputId": "fa2bdc5f-cb7d-4dc0-a526-63735e2bc5b8"
      },
      "execution_count": 17,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Searching your Google Drive for the dataset files...\n",
            "\n",
            "✅ EXACT PATH FOUND:\n",
            "base_path = \"/content/drive/MyDrive/Olist_Dataset\"\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Install DuckDB if not already present\n",
        "!pip install duckdb -q\n",
        "\n",
        "import duckdb\n",
        "import pandas as pd\n",
        "import os\n",
        "\n",
        "# Use the exact folder path where your CSVs live\n",
        "base_path = \"/content/drive/MyDrive/Olist_Dataset\"\n",
        "\n",
        "# Load dataframes safely using os.path.join\n",
        "orders = pd.read_csv(os.path.join(base_path, 'olist_orders_dataset.csv'))\n",
        "order_items = pd.read_csv(os.path.join(base_path, 'olist_order_items_dataset.csv'))\n",
        "customers = pd.read_csv(os.path.join(base_path, 'olist_customers_dataset.csv'))\n",
        "payments = pd.read_csv(os.path.join(base_path, 'olist_order_payments_dataset.csv'))\n",
        "products = pd.read_csv(os.path.join(base_path, 'olist_products_dataset.csv'))\n"
      ],
      "metadata": {
        "id": "ktAgunfrR_fh"
      },
      "execution_count": 18,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# 1. Verify the tables loaded correctly\n",
        "print(\"--- TABLES LOADED SUCCESSFULLY ---\")\n",
        "print(f\"Orders shape: {orders.shape}\")\n",
        "print(f\"Order Items shape: {order_items.shape}\")\n",
        "print(f\"Customers shape: {customers.shape}\")\n",
        "print(f\"Payments shape: {payments.shape}\")\n",
        "print(f\"Products shape: {products.shape}\\n\")\n",
        "\n",
        "# Convert order_purchase_timestamp to datetime before querying\n",
        "orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])\n",
        "\n",
        "# 2. Run Query 1: Overall Sales Performance & Monthly Trends\n",
        "query_results = duckdb.sql(\"\"\"\n",
        "    SELECT\n",
        "        DATE_TRUNC('month', o.order_purchase_timestamp) AS order_month,\n",
        "        COUNT(DISTINCT o.order_id) AS total_orders,\n",
        "        COUNT(DISTINCT o.customer_id) AS total_customers,\n",
        "        SUM(i.price + i.freight_value) AS total_revenue,\n",
        "        ROUND(SUM(i.price + i.freight_value) / COUNT(DISTINCT o.order_id), 2) AS average_order_value\n",
        "    FROM orders o\n",
        "    JOIN order_items i ON o.order_id = i.order_id\n",
        "    WHERE o.order_status NOT IN ('canceled', 'unavailable')\n",
        "    GROUP BY 1\n",
        "    ORDER BY order_month ASC;\n",
        "\"\"\").df()\n",
        "\n",
        "# 3. Print the results so you can see the table clearly in Colab\n",
        "print(\"--- QUERY 1 RESULTS (Monthly Sales & Revenue) ---\")\n",
        "print(query_results.head(12))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "o_3HgTJMTTPr",
        "outputId": "79269ba4-b63a-4a15-d83e-b30737c65f83"
      },
      "execution_count": 19,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "--- TABLES LOADED SUCCESSFULLY ---\n",
            "Orders shape: (99441, 8)\n",
            "Order Items shape: (112650, 7)\n",
            "Customers shape: (99441, 5)\n",
            "Payments shape: (103886, 5)\n",
            "Products shape: (32951, 9)\n",
            "\n",
            "--- QUERY 1 RESULTS (Monthly Sales & Revenue) ---\n",
            "   order_month  total_orders  total_customers  total_revenue  \\\n",
            "0   2016-09-01             2                2         279.69   \n",
            "1   2016-10-01           290              290       51354.52   \n",
            "2   2016-12-01             1                1          19.62   \n",
            "3   2017-01-01           787              787      136943.46   \n",
            "4   2017-02-01          1718             1718      283561.69   \n",
            "5   2017-03-01          2617             2617      425617.96   \n",
            "6   2017-04-01          2377             2377      405848.61   \n",
            "7   2017-05-01          3640             3640      582710.83   \n",
            "8   2017-06-01          3205             3205      499652.24   \n",
            "9   2017-07-01          3946             3946      578753.73   \n",
            "10  2017-08-01          4272             4272      661903.52   \n",
            "11  2017-09-01          4227             4227      717102.72   \n",
            "\n",
            "    average_order_value  \n",
            "0                139.85  \n",
            "1                177.08  \n",
            "2                 19.62  \n",
            "3                174.01  \n",
            "4                165.05  \n",
            "5                162.64  \n",
            "6                170.74  \n",
            "7                160.09  \n",
            "8                155.90  \n",
            "9                146.67  \n",
            "10               154.94  \n",
            "11               169.65  \n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# 1. Run Query 2: Product Category Revenue Performance\n",
        "category_results = duckdb.sql(\"\"\"\n",
        "    SELECT\n",
        "        p.product_category_name AS category_name,\n",
        "        COUNT(DISTINCT i.order_id) AS total_orders,\n",
        "        COUNT(i.product_id) AS total_items_sold,\n",
        "        ROUND(SUM(i.price), 2) AS gross_product_revenue,\n",
        "        ROUND(SUM(i.price + i.freight_value), 2) AS total_revenue_with_freight\n",
        "    FROM order_items i\n",
        "    JOIN products p ON i.product_id = p.product_id\n",
        "    GROUP BY 1\n",
        "    ORDER BY total_revenue_with_freight DESC\n",
        "    LIMIT 10;\n",
        "\"\"\").df()\n",
        "\n",
        "print(\"--- QUERY 2 RESULTS (Top 10 Product Categories by Revenue) ---\")\n",
        "display(category_results)\n",
        "\n",
        "\n",
        "# 2. Run Query 3: Customer State Concentration (Geographical Revenue)\n",
        "state_results = duckdb.sql(\"\"\"\n",
        "    SELECT\n",
        "        c.customer_state,\n",
        "        COUNT(DISTINCT c.customer_unique_id) AS unique_customers,\n",
        "        COUNT(DISTINCT o.order_id) AS total_orders,\n",
        "        ROUND(SUM(i.price + i.freight_value), 2) AS total_state_revenue,\n",
        "        ROUND(SUM(i.price + i.freight_value) / COUNT(DISTINCT o.order_id), 2) AS aov_per_state\n",
        "    FROM orders o\n",
        "    JOIN customers c ON o.customer_id = c.customer_id\n",
        "    JOIN order_items i ON o.order_id = i.order_id\n",
        "    WHERE o.order_status NOT IN ('canceled', 'unavailable')\n",
        "    GROUP BY 1\n",
        "    ORDER BY total_state_revenue DESC\n",
        "    LIMIT 10;\n",
        "\"\"\").df()\n",
        "\n",
        "print(\"\\n--- QUERY 3 RESULTS (Top 10 States by Revenue) ---\")\n",
        "display(state_results)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 762
        },
        "id": "lJumFWp-ToRf",
        "outputId": "5c757d0f-159a-4382-e7b1-324431647831"
      },
      "execution_count": 20,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "--- QUERY 2 RESULTS (Top 10 Product Categories by Revenue) ---\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "            category_name  total_orders  total_items_sold  \\\n",
              "0            beleza_saude          8836              9670   \n",
              "1      relogios_presentes          5624              5991   \n",
              "2         cama_mesa_banho          9417             11115   \n",
              "3           esporte_lazer          7720              8641   \n",
              "4  informatica_acessorios          6689              7827   \n",
              "5        moveis_decoracao          6449              8334   \n",
              "6   utilidades_domesticas          5884              6964   \n",
              "7              cool_stuff          3632              3796   \n",
              "8              automotivo          3897              4235   \n",
              "9      ferramentas_jardim          3518              4347   \n",
              "\n",
              "   gross_product_revenue  total_revenue_with_freight  \n",
              "0             1258681.34                  1441248.07  \n",
              "1             1205005.68                  1305541.61  \n",
              "2             1036988.68                  1241681.72  \n",
              "3              988048.97                  1156656.48  \n",
              "4              911954.32                  1059272.40  \n",
              "5              729762.49                   902511.79  \n",
              "6              632248.66                   778397.77  \n",
              "7              635290.85                   719329.95  \n",
              "8              592720.11                   685384.32  \n",
              "9              485256.46                   584219.21  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-4b3a53e1-cbe9-4e6e-b553-472a21026655\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>category_name</th>\n",
              "      <th>total_orders</th>\n",
              "      <th>total_items_sold</th>\n",
              "      <th>gross_product_revenue</th>\n",
              "      <th>total_revenue_with_freight</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>beleza_saude</td>\n",
              "      <td>8836</td>\n",
              "      <td>9670</td>\n",
              "      <td>1258681.34</td>\n",
              "      <td>1441248.07</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>relogios_presentes</td>\n",
              "      <td>5624</td>\n",
              "      <td>5991</td>\n",
              "      <td>1205005.68</td>\n",
              "      <td>1305541.61</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>cama_mesa_banho</td>\n",
              "      <td>9417</td>\n",
              "      <td>11115</td>\n",
              "      <td>1036988.68</td>\n",
              "      <td>1241681.72</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>esporte_lazer</td>\n",
              "      <td>7720</td>\n",
              "      <td>8641</td>\n",
              "      <td>988048.97</td>\n",
              "      <td>1156656.48</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>informatica_acessorios</td>\n",
              "      <td>6689</td>\n",
              "      <td>7827</td>\n",
              "      <td>911954.32</td>\n",
              "      <td>1059272.40</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>moveis_decoracao</td>\n",
              "      <td>6449</td>\n",
              "      <td>8334</td>\n",
              "      <td>729762.49</td>\n",
              "      <td>902511.79</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>utilidades_domesticas</td>\n",
              "      <td>5884</td>\n",
              "      <td>6964</td>\n",
              "      <td>632248.66</td>\n",
              "      <td>778397.77</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>cool_stuff</td>\n",
              "      <td>3632</td>\n",
              "      <td>3796</td>\n",
              "      <td>635290.85</td>\n",
              "      <td>719329.95</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>automotivo</td>\n",
              "      <td>3897</td>\n",
              "      <td>4235</td>\n",
              "      <td>592720.11</td>\n",
              "      <td>685384.32</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>ferramentas_jardim</td>\n",
              "      <td>3518</td>\n",
              "      <td>4347</td>\n",
              "      <td>485256.46</td>\n",
              "      <td>584219.21</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-4b3a53e1-cbe9-4e6e-b553-472a21026655')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-4b3a53e1-cbe9-4e6e-b553-472a21026655 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-4b3a53e1-cbe9-4e6e-b553-472a21026655');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "  <div id=\"id_7e6354c3-7589-4d0d-80d1-99006d8d0ff2\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('category_results')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_7e6354c3-7589-4d0d-80d1-99006d8d0ff2 button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('category_results');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "category_results",
              "summary": "{\n  \"name\": \"category_results\",\n  \"rows\": 10,\n  \"fields\": [\n    {\n      \"column\": \"category_name\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 10,\n        \"samples\": [\n          \"automotivo\",\n          \"relogios_presentes\",\n          \"moveis_decoracao\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"total_orders\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2092,\n        \"min\": 3518,\n        \"max\": 9417,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          3897,\n          5624,\n          6449\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"total_items_sold\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2474,\n        \"min\": 3796,\n        \"max\": 11115,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          4235,\n          5991,\n          8334\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"gross_product_revenue\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 270402.12948780775,\n        \"min\": 485256.46,\n        \"max\": 1258681.34,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          592720.11,\n          1205005.68,\n          729762.49\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"total_revenue_with_freight\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 294803.5979362512,\n        \"min\": 584219.21,\n        \"max\": 1441248.07,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          685384.32,\n          1305541.61,\n          902511.79\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "--- QUERY 3 RESULTS (Top 10 States by Revenue) ---\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "  customer_state  unique_customers  total_orders  total_state_revenue  \\\n",
              "0             SP             39747         41125           5878132.06   \n",
              "1             RJ             12241         12697           2115667.56   \n",
              "2             MG             11134         11496           1843074.43   \n",
              "3             RS              5233          5415            877290.59   \n",
              "4             PR              4824          4982            794196.61   \n",
              "5             SC              3501          3599            608023.70   \n",
              "6             BA              3244          3344            606908.66   \n",
              "7             DF              2057          2120            351327.21   \n",
              "8             GO              1934          1998            340544.37   \n",
              "9             ES              1950          2018            323081.03   \n",
              "\n",
              "   aov_per_state  \n",
              "0         142.93  \n",
              "1         166.63  \n",
              "2         160.32  \n",
              "3         162.01  \n",
              "4         159.41  \n",
              "5         168.94  \n",
              "6         181.49  \n",
              "7         165.72  \n",
              "8         170.44  \n",
              "9         160.10  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-5281a7eb-ba7a-4c04-a9de-7dceb1efe89a\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>customer_state</th>\n",
              "      <th>unique_customers</th>\n",
              "      <th>total_orders</th>\n",
              "      <th>total_state_revenue</th>\n",
              "      <th>aov_per_state</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>SP</td>\n",
              "      <td>39747</td>\n",
              "      <td>41125</td>\n",
              "      <td>5878132.06</td>\n",
              "      <td>142.93</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>RJ</td>\n",
              "      <td>12241</td>\n",
              "      <td>12697</td>\n",
              "      <td>2115667.56</td>\n",
              "      <td>166.63</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>MG</td>\n",
              "      <td>11134</td>\n",
              "      <td>11496</td>\n",
              "      <td>1843074.43</td>\n",
              "      <td>160.32</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>RS</td>\n",
              "      <td>5233</td>\n",
              "      <td>5415</td>\n",
              "      <td>877290.59</td>\n",
              "      <td>162.01</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>PR</td>\n",
              "      <td>4824</td>\n",
              "      <td>4982</td>\n",
              "      <td>794196.61</td>\n",
              "      <td>159.41</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>SC</td>\n",
              "      <td>3501</td>\n",
              "      <td>3599</td>\n",
              "      <td>608023.70</td>\n",
              "      <td>168.94</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>BA</td>\n",
              "      <td>3244</td>\n",
              "      <td>3344</td>\n",
              "      <td>606908.66</td>\n",
              "      <td>181.49</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>DF</td>\n",
              "      <td>2057</td>\n",
              "      <td>2120</td>\n",
              "      <td>351327.21</td>\n",
              "      <td>165.72</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>GO</td>\n",
              "      <td>1934</td>\n",
              "      <td>1998</td>\n",
              "      <td>340544.37</td>\n",
              "      <td>170.44</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>ES</td>\n",
              "      <td>1950</td>\n",
              "      <td>2018</td>\n",
              "      <td>323081.03</td>\n",
              "      <td>160.10</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-5281a7eb-ba7a-4c04-a9de-7dceb1efe89a')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-5281a7eb-ba7a-4c04-a9de-7dceb1efe89a button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-5281a7eb-ba7a-4c04-a9de-7dceb1efe89a');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "  <div id=\"id_96f9340a-6cc1-4ec7-8161-a3c640131c61\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('state_results')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_96f9340a-6cc1-4ec7-8161-a3c640131c61 button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('state_results');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "state_results",
              "summary": "{\n  \"name\": \"state_results\",\n  \"rows\": 10,\n  \"fields\": [\n    {\n      \"column\": \"customer_state\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 10,\n        \"samples\": [\n          \"GO\",\n          \"RJ\",\n          \"SC\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"unique_customers\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 11554,\n        \"min\": 1934,\n        \"max\": 39747,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          1934,\n          12241,\n          3501\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"total_orders\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 11958,\n        \"min\": 1998,\n        \"max\": 41125,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          1998,\n          12697,\n          3599\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"total_state_revenue\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1700773.313589872,\n        \"min\": 323081.03,\n        \"max\": 5878132.06,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          340544.37,\n          2115667.56,\n          608023.7\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"aov_per_state\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 9.882499065407384,\n        \"min\": 142.93,\n        \"max\": 181.49,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          170.44,\n          166.63,\n          168.94\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Run Query 4: Payment Method Distribution & Revenue Share\n",
        "payment_results = duckdb.sql(\"\"\"\n",
        "    SELECT\n",
        "        p.payment_type,\n",
        "        COUNT(DISTINCT p.order_id) AS total_orders_using_method,\n",
        "        ROUND(SUM(p.payment_value), 2) AS total_revenue_collected,\n",
        "        ROUND(100.0 * SUM(p.payment_value) / SUM(SUM(p.payment_value)) OVER(), 2) AS percentage_revenue_share\n",
        "    FROM payments p\n",
        "    WHERE p.payment_type NOT IN ('not_defined')\n",
        "      AND p.payment_value > 0\n",
        "    GROUP BY 1\n",
        "    ORDER BY total_revenue_collected DESC;\n",
        "\"\"\").df()\n",
        "\n",
        "print(\"--- QUERY 4 RESULTS (Payment Methods & Revenue Share) ---\")\n",
        "display(payment_results)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 193
        },
        "id": "3eMwzX7lTqi0",
        "outputId": "6194e941-6778-4508-8fa4-95e8617d1f29"
      },
      "execution_count": 21,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "--- QUERY 4 RESULTS (Payment Methods & Revenue Share) ---\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "  payment_type  total_orders_using_method  total_revenue_collected  \\\n",
              "0  credit_card                      76505              12542084.19   \n",
              "1       boleto                      19784               2869361.27   \n",
              "2      voucher                       3866                379436.87   \n",
              "3   debit_card                       1528                217989.79   \n",
              "\n",
              "   percentage_revenue_share  \n",
              "0                     78.34  \n",
              "1                     17.92  \n",
              "2                      2.37  \n",
              "3                      1.36  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-f39d2442-ee92-4a3e-9d2a-d21d49c7eb6e\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>payment_type</th>\n",
              "      <th>total_orders_using_method</th>\n",
              "      <th>total_revenue_collected</th>\n",
              "      <th>percentage_revenue_share</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>credit_card</td>\n",
              "      <td>76505</td>\n",
              "      <td>12542084.19</td>\n",
              "      <td>78.34</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>boleto</td>\n",
              "      <td>19784</td>\n",
              "      <td>2869361.27</td>\n",
              "      <td>17.92</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>voucher</td>\n",
              "      <td>3866</td>\n",
              "      <td>379436.87</td>\n",
              "      <td>2.37</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>debit_card</td>\n",
              "      <td>1528</td>\n",
              "      <td>217989.79</td>\n",
              "      <td>1.36</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-f39d2442-ee92-4a3e-9d2a-d21d49c7eb6e')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-f39d2442-ee92-4a3e-9d2a-d21d49c7eb6e button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-f39d2442-ee92-4a3e-9d2a-d21d49c7eb6e');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "  <div id=\"id_7fd3c578-a602-42da-8729-cbcdc9879676\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('payment_results')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_7fd3c578-a602-42da-8729-cbcdc9879676 button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('payment_results');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "payment_results",
              "summary": "{\n  \"name\": \"payment_results\",\n  \"rows\": 4,\n  \"fields\": [\n    {\n      \"column\": \"payment_type\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 4,\n        \"samples\": [\n          \"boleto\",\n          \"debit_card\",\n          \"credit_card\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"total_orders_using_method\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 35008,\n        \"min\": 1528,\n        \"max\": 76505,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          19784,\n          1528,\n          76505\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"total_revenue_collected\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 5821156.963326543,\n        \"min\": 217989.79,\n        \"max\": 12542084.19,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          2869361.27,\n          217989.79,\n          12542084.19\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"percentage_revenue_share\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 36.360456886568414,\n        \"min\": 1.36,\n        \"max\": 78.34,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          17.92,\n          1.36,\n          78.34\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "import os\n",
        "\n",
        "# Ensure product_category_name_translation is loaded\n",
        "# The base_path variable should be available from previous cells\n",
        "product_category_name_translation = pd.read_csv(os.path.join(base_path, 'product_category_name_translation.csv'))\n",
        "\n",
        "# 1. Export Monthly Sales Trends\n",
        "monthly_sales = duckdb.sql(\"\"\"\n",
        "    SELECT\n",
        "        DATE_TRUNC('month', o.order_purchase_timestamp) AS order_month,\n",
        "        COUNT(DISTINCT o.order_id) AS total_orders,\n",
        "        COUNT(DISTINCT o.customer_id) AS total_customers,\n",
        "        SUM(i.price + i.freight_value) AS total_revenue,\n",
        "        ROUND(SUM(i.price + i.freight_value) / COUNT(DISTINCT o.order_id), 2) AS average_order_value\n",
        "    FROM orders o\n",
        "    JOIN order_items i ON o.order_id = i.order_id\n",
        "    WHERE o.order_status NOT IN ('canceled', 'unavailable')\n",
        "    GROUP BY 1\n",
        "    ORDER BY order_month ASC;\n",
        "\"\"\").df()\n",
        "monthly_sales.to_csv('olist_monthly_sales.csv', index=False)\n",
        "\n",
        "# 2. Export Top Product Categories\n",
        "category_performance = duckdb.sql(\"\"\"\n",
        "    SELECT\n",
        "        COALESCE(t.product_category_name_english, p.product_category_name, 'unknown') AS category_name,\n",
        "        COUNT(DISTINCT i.order_id) AS total_orders,\n",
        "        COUNT(i.product_id) AS total_items_sold,\n",
        "        ROUND(SUM(i.price), 2) AS gross_product_revenue,\n",
        "        ROUND(SUM(i.price + i.freight_value), 2) AS total_revenue_with_freight\n",
        "    FROM order_items i\n",
        "    JOIN products p ON i.product_id = p.product_id\n",
        "    LEFT JOIN product_category_name_translation t ON p.product_category_name = t.product_category_name\n",
        "    GROUP BY 1\n",
        "    ORDER BY total_revenue_with_freight DESC\n",
        "    LIMIT 15;\n",
        "\"\"\").df()\n",
        "category_performance.to_csv('olist_category_performance.csv', index=False)\n",
        "\n",
        "# 3. Export Geographical State Revenue\n",
        "state_revenue = duckdb.sql(\"\"\"\n",
        "    SELECT\n",
        "        c.customer_state,\n",
        "        COUNT(DISTINCT c.customer_unique_id) AS unique_customers,\n",
        "        COUNT(DISTINCT o.order_id) AS total_orders,\n",
        "        ROUND(SUM(i.price + i.freight_value), 2) AS total_state_revenue,\n",
        "        ROUND(SUM(i.price + i.freight_value) / COUNT(DISTINCT o.order_id), 2) AS aov_per_state\n",
        "    FROM orders o\n",
        "    JOIN customers c ON o.customer_id = c.customer_id\n",
        "    JOIN order_items i ON o.order_id = i.order_id\n",
        "    WHERE o.order_status NOT IN ('canceled', 'unavailable')\n",
        "    GROUP BY 1\n",
        "    ORDER BY total_state_revenue DESC;\n",
        "\"\"\").df()\n",
        "state_revenue.to_csv('olist_state_revenue.csv', index=False)\n",
        "\n",
        "# 4. Export Payment Methods Distribution\n",
        "payment_share = duckdb.sql(\"\"\"\n",
        "    SELECT\n",
        "        p.payment_type,\n",
        "        COUNT(DISTINCT p.order_id) AS total_orders_using_method,\n",
        "        ROUND(SUM(p.payment_value), 2) AS total_revenue_collected,\n",
        "        ROUND(100.0 * SUM(p.payment_value) / SUM(SUM(p.payment_value)) OVER(), 2) AS percentage_revenue_share\n",
        "    FROM payments p\n",
        "    WHERE p.payment_type NOT IN ('not_defined')\n",
        "      AND p.payment_value > 0\n",
        "    GROUP BY 1\n",
        "    ORDER BY total_revenue_collected DESC;\n",
        "\"\"\").df()\n",
        "payment_share.to_csv('olist_payment_share.csv', index=False)\n",
        "\n",
        "print(\"✅ All 4 core analytical tables exported successfully as CSVs!\")\n",
        "\n",
        "# Optional: Auto-download files to your Mac if running in browser Colab\n",
        "from google.colab import files\n",
        "files.download('olist_monthly_sales.csv')\n",
        "files.download('olist_category_performance.csv')\n",
        "files.download('olist_state_revenue.csv')\n",
        "files.download('olist_payment_share.csv')"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 35
        },
        "id": "C6LN0eQ2ZFey",
        "outputId": "fbb0b481-2157-437b-c392-2b5652ff62f6"
      },
      "execution_count": 23,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ All 4 core analytical tables exported successfully as CSVs!\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_9e42f7e5-272b-46d8-94cd-46a39bc7b03a\", \"olist_monthly_sales.csv\", 1120)"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_c838ca80-2c62-475c-ab18-94010f027787\", \"olist_category_performance.csv\", 731)"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_957eb92e-1076-4737-8cb9-4e1ff82435f1\", \"olist_state_revenue.csv\", 845)"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_34f1dbec-6bfe-4188-942b-8ea466067c87\", \"olist_payment_share.csv\", 213)"
            ]
          },
          "metadata": {}
        }
      ]
    }
  ]
}